spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vhrprod?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8082

mybatis:
  type-aliases-package: ga.yiwa.vhrmodel
  mapper-locations: ga/yiwa/vhrmapper/*.xml
  configuration:
    map-underscore-to-camel-case: true